name: "Tests"

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    test:
        name: "${{ matrix.operating-system }} / PHP ${{ matrix.php-version }}"
        runs-on: ${{ matrix.operating-system }}
        continue-on-error: false

        strategy:
            matrix:
                operating-system: ['ubuntu-latest']
                php-version: ['8.1','8.2']

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php-version }}
                coverage: pcov

            - name: "Set composer cache directory"
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
              shell: bash

            - name: "Cache composer"
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

            - name: "Install dependencies"
              run: composer install --no-interaction --no-progress

            - name: "PHPUnit version"
              run: vendor/bin/phpunit --version

            - name: "Run Coding standard"
              run: vendor/bin/php-cs-fixer fix --verbose --dry-run

            - name: "Run Psalm"
              run: vendor/bin/psalm

            - name: "Run tests"
              run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

            - name: Upload coverage report to Coveralls
              run: vendor/bin/coveralls.php --service=github --coverage_clover=build/logs/clover.xml -v
              env:
                COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
